default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port:     <%= ENV.fetch('DB_PORT') { 5432 } %>
  sslmode:  require

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
