source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.2.0'

gem 'rails', '~> 8.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'jsonapi-serializer'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt', '~> 2.7'
gem 'pagy', '~> 6.0'
gem 'rack-cors'
gem 'dotenv-rails', groups: [:development, :test]
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'annotate'
end
